// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE8xE81zb5y4154hQbMB-CZxLQgGZVdws',
    appId: '1:475735943347:web:0fd04f67500b5f583528c6',
    messagingSenderId: '475735943347',
    projectId: 'rozgar-25d03',
    authDomain: 'rozgar-25d03.firebaseapp.com',
    storageBucket: 'rozgar-25d03.firebasestorage.app',
    measurementId: 'G-1WN4E2ZP41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGdK8D-JKFQTIl_73PyePD1gmVJCq3v8E',
    appId: '1:475735943347:android:d8b1606cc9309fe93528c6',
    messagingSenderId: '475735943347',
    projectId: 'rozgar-25d03',
    storageBucket: 'rozgar-25d03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnIndiJxHnTi_zq3QG-lEY_DOuKXSzx90',
    appId: '1:475735943347:ios:496add3f7c1776c43528c6',
    messagingSenderId: '475735943347',
    projectId: 'rozgar-25d03',
    storageBucket: 'rozgar-25d03.firebasestorage.app',
    iosBundleId: 'com.example.rozgar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnIndiJxHnTi_zq3QG-lEY_DOuKXSzx90',
    appId: '1:475735943347:ios:496add3f7c1776c43528c6',
    messagingSenderId: '475735943347',
    projectId: 'rozgar-25d03',
    storageBucket: 'rozgar-25d03.firebasestorage.app',
    iosBundleId: 'com.example.rozgar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE8xE81zb5y4154hQbMB-CZxLQgGZVdws',
    appId: '1:475735943347:web:3ca90ec01350686e3528c6',
    messagingSenderId: '475735943347',
    projectId: 'rozgar-25d03',
    authDomain: 'rozgar-25d03.firebaseapp.com',
    storageBucket: 'rozgar-25d03.firebasestorage.app',
    measurementId: 'G-NZ5FQNYQVE',
  );
}
