// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZKiIPlyjsGpNdqCvqmL76_cOGd7JT8fs',
    appId: '1:1001430347996:web:d1a1d185e4ed29ab20c419',
    messagingSenderId: '1001430347996',
    projectId: 'rozgar-6abea',
    authDomain: 'rozgar-6abea.firebaseapp.com',
    storageBucket: 'rozgar-6abea.firebasestorage.app',
    measurementId: 'G-9VZCN5DHRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA4Ay6X0wjJ3czzEI_KSwaxRzQTcBi03Y',
    appId: '1:1001430347996:android:24e5e3b4a57bc4f020c419',
    messagingSenderId: '1001430347996',
    projectId: 'rozgar-6abea',
    storageBucket: 'rozgar-6abea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZKiIPlyjsGpNdqCvqmL76_cOGd7JT8fs',
    appId: '1:1001430347996:web:d1a1d185e4ed29ab20c419',
    messagingSenderId: '1001430347996',
    projectId: 'rozgar-6abea',
    storageBucket: 'rozgar-6abea.firebasestorage.app',
    iosBundleId: 'com.example.rozgar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZKiIPlyjsGpNdqCvqmL76_cOGd7JT8fs',
    appId: '1:1001430347996:web:d1a1d185e4ed29ab20c419',
    messagingSenderId: '1001430347996',
    projectId: 'rozgar-6abea',
    storageBucket: 'rozgar-6abea.firebasestorage.app',
    iosBundleId: 'com.example.rozgar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZKiIPlyjsGpNdqCvqmL76_cOGd7JT8fs',
    appId: '1:1001430347996:web:d1a1d185e4ed29ab20c419',
    messagingSenderId: '1001430347996',
    projectId: 'rozgar-6abea',
    authDomain: 'rozgar-6abea.firebaseapp.com',
    storageBucket: 'rozgar-6abea.firebasestorage.app',
    measurementId: 'G-9VZCN5DHRS',
  );
}
